spring:
  profiles:
    active: home2
  application:
    name: cloud-service
server:
  port: 8081
logging:
  level:
    root: debug


---
# company

spring:
  profiles: company
cn:
  exceptioncode:
    api:
      code:
        doc:
          controller-base-package: cn.excptioncode.webapp.controller
          api-catid: 12
          api-server: 127.0.0.1:3000
          api-token: bc30a4d684908840d42d9bb094e0891f8f778a01be2c15aa9ef27c53e8d2bf23
          api-user-name: 425485346@qq.com
          api-user-password: ymfe.org
          enable: true


---
# home

spring:
  profiles: home
cn:
  exceptioncode:
    api:
      code:
        doc:
          controller-base-package: cn.excptioncode.webapp.controller
          api-catid: 11
          api-server: 192.168.0.104:3000
          api-token: 94677a30c3e3fa0a19609c9629b13aa0f46b91a8b9bfd45e482235751d615b22
          api-user-name: 425485346@qq.com
          api-user-password: ymfe.org
          enable: true

---
# home2

spring:
  profiles: home2
cn:
  exceptioncode:
    api:
      code:
        doc:
          controller-base-package: cn.excptioncode.webapp.controller
          api-catid: 11
          api-server: 127.0.0.1:3000
          api-token: 94677a30c3e3fa0a19609c9629b13aa0f46b91a8b9bfd45e482235751d615b22
          api-user-name: 425485346@qq.com
          api-user-password: ymfe.org
          enable: true