spring:
#  profiles:
#    active: home2
  application:
    name: cloud-service
server:
  port: 8081
logging:
  level:
    root: info


---
# company

spring:
  profiles: company
cn:
  exceptioncode:
    yapi:
      client:
        api-catid: 12
        api-server: 127.0.0.1:3000
        api-token: bc30a4d684908840d42d9bb094e0891f8f778a01be2c15aa9ef27c53e8d2bf23
        api-user-name: 425485346@qq.com
        api-user-password: ymfe.org
        enable: true


---
# home

spring:
  profiles: home
cn:
  exceptioncode:
    yapi:
      client:
        api-catid: 12
        api-server: 127.0.0.1:3000
        api-token: bc30a4d684908840d42d9bb094e0891f8f778a01be2c15aa9ef27c53e8d2bf23
        api-user-name: 425485346@qq.com
        api-user-password: ymfe.org
        enable: true

---
# home2

spring:
  profiles: home2
cn:
  exceptioncode:
    yapi:
      client:
        api-catid: 12
        api-server: 127.0.0.1:3000
        api-token: bc30a4d684908840d42d9bb094e0891f8f778a01be2c15aa9ef27c53e8d2bf23
        api-user-name: 425485346@qq.com
        api-user-password: ymfe.org
        enable: true