spring:
  application:
    name: gateway
  redis:
    host: 0.tcp.ngrok.io
    port: 15522
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway