spring:
  application:
    name: gateway
  redis:
    host: 127.0.0.1
    password:
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway