spring:
  application:
    name: gateway
  redis:
    host: dev.iotechina.com
    password: GTMCmy123
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway